#!/bin/sh
#
# release
#
# generates release files:
#   editions\release\output\TW5Roboto.html -- the plugin demo wiki
#   editions\release\output\TW5Roboto.tid -- the plugin tiddler
#
tiddlywiki \
	editions/release \
	--verbose \
	--build release
